### PR TITLE
Add babashka compatibility

### PR DESCRIPTION
**Pull request by borkdude**
As discussed on Slack, here is a PR that adds babashka compatibility.

On top of the compatibility commit, I added the following:

- Run babashka tests in Github Actions to prevent future breakage.
- Run other leiningen tests in Github Actions as well.

If any of that is too much, I would be happy to remove/change it.

### CODE REVIEW

**Comment by nathanmarz** [comment]
Is it possible to run the babashka tests instead in the existing travis ci setup?

**Comment by borkdude** [comment]
@nathanmarz Yes, I can do that.

**Comment by borkdude** [comment]
I changed the PR but I don't know how to run it on Travis myself. It seems PRs do not have the Travis build activated?

**Comment by borkdude** [comment]
I can make a more minimal pr that leaves out `deps.edn` and `bb.edn` as well, if you want.

**Comment by nathanmarz** [comment]
Took at look at the travis setup, and it looks like they made some changes and I can't even login to administer the build setup. So on second thought, would it be hard to remove travis completely and convert the build to run on Github Actions entirely?

I think it's best to remove the .edn files as well if they're not necessary.

**Comment by borkdude** [comment]
> I think it's best to remove the .edn files as well if they're not necessary.

They are kind of necessary:

- The `deps.edn` file is necessary to run the code as a git dependency in babashka, but it can be removed once this is published to maven. I'll remove this file.
- The `bb.edn` file is necessary to run the babashka tasks, but I can move that to a `test/runner.bb` file. I guess this doesn't matter much, since it's a new file either way.

I will close this PR and make a new one as a clean up.

**Comment by borkdude** [comment]
A new PR here: https://github.com/redplanetlabs/specter/pull/323

**Pull request closed without merging**
