### PR TITLE
Add babashka compatibility

### PR DESCRIPTION
**Pull request by borkdude**
This PR also moves the CI setup from travis to Github Actions.

### CODE REVIEW

**Comment by borkdude** [comment]
@nathanmarz Github Actions will probably start running once you merge this to master. In some cases you still have to enable it in Settings of the repo. You can see [here](https://github.com/borkdude/specter/runs/5539992719?check_suite_focus=true) that the tests run correctly on my end of the PR.

**Comment by borkdude** [comment]
Done!

**Comment by nathanmarz** [comment]
Thanks!

**Comment by borkdude** [comment]
Thank you too! Looking forward to 1.1.4 so I can mention that in the babashka changelogs :).

**Pull request merged**
