### PR TITLE
Fix comment on manual clojure example, it does actually work

### PR DESCRIPTION
**Pull request by AndreaCrotti**
> (def data [1 2 3 4 5 6 7 8])
> (map inc data)
(2 3 4 5 6 7 8 9)
> (into (empty data) (map inc data))
[2 3 4 5 6 7 8 9]
> (sp/transform sp/ALL inc data)
[2 3 4 5 6 7 8 9]

### CODE REVIEW

**Comment by nathanmarz** [comment]
As it says in the example, it reverses the order of lists:

```
user=> (def data '(1 2 3 4 5 6 7 8))
#'user/data
user=> (into (empty data) (map inc data))
(9 8 7 6 5 4 3 2)
```

**Comment by AndreaCrotti** [comment]
> As it says in the example, it reverses the order of lists:
> 
> ```
> user=> (def data '(1 2 3 4 5 6 7 8))
> #'user/data
> user=> (into (empty data) (map inc data))
> (9 8 7 6 5 4 3 2)
> ```

It reverses the order if you use a list, but not if you use a vector, and in the readme the data is defined as a vector not a list, so it's not true that it reverses the order in that case.

```(def data [1 2 3 4 5 6 7 8])

;; Manual Clojure
(let [idx (reduce-kv (fn [res i v] (if (odd? v) i res)) nil data)]
  (if idx (update data idx inc) data))

;; Specter
(transform [(filterer odd?) LAST] inc data)
```

**Example 4: Map a function over a sequence without changing the type or order of the sequence**

```clojure
;; Manual Clojure
(map inc data) ;; doesn't work, becomes a lazy sequence

(into (empty data) (map inc data)) ;; works correctly
```

**Comment by nathanmarz** [comment]
The example doesn't define `data`. I think you're looking at the previous example. This example is about having a generic way to map a function over any sequence type without changing the type or order of it.

**Comment by AndreaCrotti** [comment]
> The example doesn't define `data`. I think you're looking at the previous example. This example is about having a generic way to map a function over any sequence type without changing the type or order of it.

Yeah I simply looked at the previous time where `data` was defined, assuming it was just reusing the same var.
I understand now, but I think it would be clearer to redefine data as a list just above the Example 4, so it's clear what it actually is.

**Pull request closed without merging**
